const moviesEnglish = [
  { id: 1, title: "Inception", language: "English", genre: ["Sci-Fi", "Thriller", "Action"], year: 2010, rating: 8.8, plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", poster: "posters/inception.jpg", cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Tom Hardy"], duration: "2h 28m" },
  { id: 2, title: "The Dark Knight", language: "English", genre: ["Action", "Thriller", "Drama"], year: 2008, rating: 9.0, plot: "When the menace known as the Joker wreaks havoc and chaos on Gotham, Batman must accept one of the greatest tests to fight injustice.", poster: "posters/dark_knight.jpg", cast: ["Christian Bale", "Heath Ledger", "Gary Oldman"], duration: "2h 32m" },
  { id: 3, title: "The Conjuring", language: "English", genre: ["Horror", "Thriller"], year: 2013, rating: 7.5, plot: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.", poster: "posters/conjuring.jpg", cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor"], duration: "1h 52m" },
  { id: 4, title: "Superbad", language: "English", genre: ["Comedy"], year: 2007, rating: 7.6, plot: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a party goes awry.", poster: "posters/superbad.png", cast: ["Jonah Hill", "Michael Cera", "Seth Rogen"], duration: "1h 53m" },
  { id: 5, title: "Interstellar", language: "English", genre: ["Sci-Fi", "Drama"], year: 2014, rating: 8.7, plot: "When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.", poster: "posters/interstellar.jpg", cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"], duration: "2h 49m" },
  { id: 6, title: "Knives Out", language: "English", genre: ["Comedy", "Thriller", "Drama"], year: 2019, rating: 7.9, plot: "A detective investigates the death of the patriarch of an eccentric, combative family in this modern whodunnit.", poster: "posters/knives_out.png", cast: ["Daniel Craig", "Ana de Armas", "Chris Evans"], duration: "2h 10m" },
  { id: 21, title: "The Shawshank Redemption", language: "English", genre: ["Drama"], year: 1994, rating: 9.3, plot: "Over the course of several years, two convicts form a friendship, seeking consolation and redemption through basic compassion.", poster: "posters/shawshank.jpg", cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"], duration: "2h 22m" },
  { id: 22, title: "The Godfather", language: "English", genre: ["Drama"], year: 1972, rating: 9.2, plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", poster: "posters/godfather.jpg", cast: ["Marlon Brando", "Al Pacino", "James Caan"], duration: "2h 55m" },
  { id: 23, title: "Pulp Fiction", language: "English", genre: ["Thriller"], year: 1994, rating: 8.9, plot: "The lives of mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in tales of violence.", poster: "posters/pulp_fiction.jpg", cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"], duration: "2h 34m" },
  { id: 24, title: "The Matrix", language: "English", genre: ["Action", "Sci-Fi"], year: 1999, rating: 8.7, plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", poster: "posters/matrix.jpg", cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"], duration: "2h 16m" },
  { id: 25, title: "Forrest Gump", language: "English", genre: ["Drama", "Comedy"], year: 1994, rating: 8.8, plot: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75.", poster: "posters/forrest_gump.jpg", cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"], duration: "2h 22m" },
  { id: 26, title: "Gladiator", language: "English", genre: ["Action", "Drama"], year: 2000, rating: 8.5, plot: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", poster: "posters/gladiator.jpg", cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"], duration: "2h 35m" },
  { id: 27, title: "Avatar", language: "English", genre: ["Action", "Sci-Fi"], year: 2009, rating: 7.9, plot: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between orders and protecting Pandora.", poster: "posters/avatar.jpg", cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"], duration: "2h 42m" },
  { id: 28, title: "Titanic", language: "English", genre: ["Drama"], year: 1997, rating: 7.9, plot: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", poster: "posters/titanic.jpg", cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"], duration: "3h 14m" },
  { id: 29, title: "Jurassic Park", language: "English", genre: ["Sci-Fi", "Action"], year: 1993, rating: 8.2, plot: "A pragmatic paleontologist touring an island theme park is tasked with protecting kids after a major power failure.", poster: "posters/jurassic_park.jpg", cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum"], duration: "2h 7m" },
  { id: 30, title: "Avengers: Endgame", language: "English", genre: ["Action", "Sci-Fi"], year: 2019, rating: 8.4, plot: "After the devastating events of Infinity War, the remaining allies assemble once more to reverse Thanos' actions.", poster: "posters/endgame.jpg", cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"], duration: "3h 1m" }
];

window.moviesEnglish = moviesEnglish;
