const moviesTelugu = [
  { id: 13, title: "Baahubali: The Beginning", language: "Telugu", genre: ["Action", "Drama"], year: 2015, rating: 8.0, plot: "A child from the kingdom of Mahishmati uncovers his royal heritage, seeking to overthrow a tyrant king.", poster: "posters/baahubali.jpg", cast: ["Prabhas", "Rana Daggubati", "Anushka Shetty"], duration: "2h 39m" },
  { id: 14, title: "RRR", language: "Telugu", genre: ["Action", "Drama"], year: 2022, rating: 7.8, plot: "A fearless warrior and a steely cop cross paths and forge an unlikely friendship in colonial India.", poster: "posters/rrr.jpg", cast: ["NTR Jr.", "Ram Charan", "Alia Bhatt"], duration: "3h 7m" },
  { id: 15, title: "Arjun Reddy", language: "Telugu", genre: ["Drama"], year: 2017, rating: 8.0, plot: "A short-tempered medical student falls in love, but their separation plunges him into self-destruction.", poster: "posters/arjun_reddy.jpg", cast: ["Vijay Deverakonda", "Shalini Pandey", "Rahul Ramakrishna"], duration: "3h 2m" },
  { id: 16, title: "Pushpa: The Rise", language: "Telugu", genre: ["Action", "Thriller"], year: 2021, rating: 7.6, plot: "A coolie rises through the ranks of a sandalwood smuggling syndicate, making powerful enemies.", poster: "posters/pushpa.jpg", cast: ["Allu Arjun", "Rashmika Mandanna", "Fahadh Faasil"], duration: "2h 59m" },
  { id: 17, title: "Eega", language: "Telugu", genre: ["Sci-Fi", "Action", "Comedy"], year: 2012, rating: 7.7, plot: "A murdered man is reincarnated as a housefly and seeks revenge on the industrialist who killed him.", poster: "posters/eega.jpg", cast: ["Nani", "Samantha Ruth Prabhu", "Sudeep"], duration: "2h 14m" },
  { id: 18, title: "Geetha Govindam", language: "Telugu", genre: ["Comedy", "Drama"], year: 2018, rating: 7.7, plot: "A young lecturer falls in love with a woman who initially misjudges his character, leading to comedy and romance.", poster: "posters/geetha_govindam.jpg", cast: ["Vijay Deverakonda", "Rashmika Mandanna", "Subbaraju"], duration: "2h 22m" },
  { id: 19, title: "HIT: The First Case", language: "Telugu", genre: ["Thriller"], year: 2020, rating: 7.7, plot: "A police officer battles severe PTSD while investigating the mysterious disappearance of a college girl.", poster: "posters/hit.jpg", cast: ["Vishwak Sen", "Ruhani Sharma", "Murali Sharma"], duration: "2h 15m" },
  { id: 20, title: "Masooda", language: "Telugu", genre: ["Horror", "Thriller"], year: 2022, rating: 7.2, plot: "An engineer gets dragged into helping a single mother save her daughter possessed by a malevolent spirit.", poster: "posters/masooda.jpg", cast: ["Sangitha", "Thiruveer", "Kavya Kalyanram"], duration: "2h 40m" },
  { id: 41, title: "Mahanati", language: "Telugu", genre: ["Drama"], year: 2018, rating: 8.5, plot: "The biography of legendary South Indian actress Savitri, chronicling her rise to fame and tragic downfall.", poster: "posters/mahanati.jpg", cast: ["Keerthy Suresh", "Dulquer Salmaan", "Samantha Ruth Prabhu"], duration: "2h 57m" },
  { id: 42, title: "Jersey", language: "Telugu", genre: ["Drama"], year: 2019, rating: 8.6, plot: "A failed 36-year-old cricketer decides to return to the game to fulfill his young son's wish for a team jersey.", poster: "posters/jersey.jpg", cast: ["Nani", "Shraddha Srinath", "Sathyaraj"], duration: "2h 37m" },
  { id: 43, title: "Sita Ramam", language: "Telugu", genre: ["Drama", "Thriller"], year: 2022, rating: 8.6, plot: "An orphan soldier serving in Kashmir receives anonymous love letters from Sita, starting a romance.", poster: "posters/sita_ramam.jpg", cast: ["Dulquer Salmaan", "Mrunal Thakur", "Rashmika Mandanna"], duration: "2h 43m" },
  { id: 44, title: "Karthikeya 2", language: "Telugu", genre: ["Thriller", "Action"], year: 2022, rating: 7.4, plot: "A doctor gets caught in a dangerous chase to find a legendary ornament of Lord Krishna in the Himalayas.", poster: "posters/karthikeya2.jpg", cast: ["Anupama Parameswaran", "Nikhil Siddharth", "Srinivas Reddy"], duration: "2h 25m" },
  { id: 45, title: "Magadheera", language: "Telugu", genre: ["Action", "Drama"], year: 2009, rating: 7.7, plot: "A stuntman reincarnates 400 years later to rescue the princess of his past life from a villain.", poster: "posters/magadheera.jpg", cast: ["Ram Charan", "Kajal Aggarwal", "Dev Gill"], duration: "2h 46m" },
  { id: 46, title: "Rangasthalam", language: "Telugu", genre: ["Drama", "Action"], year: 2018, rating: 8.4, plot: "A deaf villager and his brother set out to overthrow a landlord who has ruled their village with fear.", poster: "posters/rangasthalam.jpg", cast: ["Ram Charan", "Samantha Ruth Prabhu", "Aadhi Pinisetty"], duration: "2h 59m" },
  { id: 47, title: "Oopiri", language: "Telugu", genre: ["Comedy", "Drama"], year: 2016, rating: 8.0, plot: "A quadriplegic billionaire entrepreneur and his street-smart ex-convict caregiver form an unlikely bond.", poster: "posters/oopiri.jpg", cast: ["Nagarjuna Akkineni", "Karthi", "Tamannaah Bhatia"], duration: "2h 38m" },
  { id: 48, title: "Athadu", language: "Telugu", genre: ["Action", "Drama"], year: 2005, rating: 8.2, plot: "A professional hitman takes the place of a deceased man in his family village to hide from police.", poster: "posters/athadu.jpg", cast: ["Mahesh Babu", "Trisha Krishnan", "Sonu Sood"], duration: "2h 52m" },
  { id: 49, title: "C/o Kancharapalem", language: "Telugu", genre: ["Drama"], year: 2018, rating: 8.9, plot: "Four unconventional love stories spanning different age groups, religions, and status in a small town.", poster: "posters/kancharapalem.jpg", cast: ["Subba Rao", "Radha Bessey", "Kesava Karri"], duration: "2h 22m" },
  { id: 50, title: "Bommarillu", language: "Telugu", genre: ["Comedy", "Drama"], year: 2006, rating: 8.2, plot: "A young man struggles against his overbearing father micro-managing him, until he falls in love.", poster: "posters/bommarillu.jpg", cast: ["Siddharth", "Genelia D'Souza", "Prakash Raj"], duration: "2h 50m" }
];

window.moviesTelugu = moviesTelugu;
