const moviesTamil = [
  { id: 51, title: "Vikram", language: "Tamil", genre: ["Action", "Thriller"], year: 2022, rating: 8.3, plot: "A black-ops squad agent investigates a serial killer group, discovering a massive drug syndicate led by a ruthless kingpin.", poster: "posters/vikram.jpg", cast: ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil"], duration: "2h 53m" },
  { id: 52, title: "Jai Bhim", language: "Tamil", genre: ["Drama"], year: 2021, rating: 8.8, plot: "A crusading lawyer fights for justice when a tribal man is falsely accused of theft and disappears from police custody.", poster: "posters/jai_bhim.jpg", cast: ["Suriya", "Lijomol Jose", "Manikandan"], duration: "2h 44m" },
  { id: 53, title: "Asuran", language: "Tamil", genre: ["Action", "Drama"], year: 2019, rating: 8.5, plot: "A peaceful farmer flees into the forests with his teenage son to protect him after the boy kills a wealthy landlord in an act of revenge.", poster: "posters/asuran.jpg", cast: ["Dhanush", "Manju Warrier", "Ken Karunas"], duration: "2h 21m" },
  { id: 54, title: "Kaithi", language: "Tamil", genre: ["Thriller", "Action"], year: 2019, rating: 8.5, plot: "A recently released prisoner drives a truck full of unconscious poisoned police officers to save their lives in exchange for meeting his daughter.", poster: "posters/kaithi.jpg", cast: ["Karthi", "Narain", "Arjun Das"], duration: "2h 25m" },
  { id: 55, title: "96", language: "Tamil", genre: ["Drama"], year: 2018, rating: 8.5, plot: "Two high school sweethearts meet again after 22 years during a school reunion, spending a nostalgic night reminiscing about their past.", poster: "posters/96.jpg", cast: ["Vijay Sethupathi", "Trisha Krishnan", "Adithya Bhaskar"], duration: "2h 30m" },
  { id: 56, title: "Nayagan", language: "Tamil", genre: ["Drama", "Action"], year: 1987, rating: 8.6, plot: "A young boy from Tamil Nadu flees to Mumbai and rises to become a powerful, benevolent godfather-like figure in the slums of Dharavi.", poster: "posters/nayagan.jpg", cast: ["Kamal Haasan", "Saranya Ponvannan", "Karthika"], duration: "2h 25m" },
  { id: 57, title: "Soodhu Kavvum", language: "Tamil", genre: ["Comedy", "Thriller"], year: 2013, rating: 8.3, plot: "A low-profile kidnapper and his crew accidentally kidnap the son of an honest politician, turning their world upside down.", poster: "posters/soodhu_kavvum.jpg", cast: ["Vijay Sethupathi", "Sanchita Shetty", "Radha Ravi"], duration: "2h 17m" },
  { id: 58, title: "Vada Chennai", language: "Tamil", genre: ["Action", "Thriller"], year: 2018, rating: 8.4, plot: "A talented young carrom player is reluctantly pulled into a dangerous local gang war in the slums of North Chennai.", poster: "posters/vada_chennai.jpg", cast: ["Dhanush", "Ameer Sultan", "Andrea Jeremiah"], duration: "2h 44m" },
  { id: 59, title: "Dhuruvangal Pathinaaru", language: "Tamil", genre: ["Thriller"], year: 2016, rating: 8.2, plot: "A retired police inspector recounts the final, mysterious case of his career that resulted in his leg amputation.", poster: "posters/d16.jpg", cast: ["Rahman", "Prakash Raghavan", "Sharath Kumar"], duration: "1h 45m" },
  { id: 60, title: "Super Deluxe", language: "Tamil", genre: ["Drama", "Thriller"], year: 2019, rating: 8.3, plot: "An array of quirky stories involving a trans woman returning to her family, a cheating wife, and boys discovering an adult film intertwine.", poster: "posters/super_deluxe.jpg", cast: ["Vijay Sethupathi", "Fahadh Faasil", "Samantha Ruth Prabhu"], duration: "2h 56m" }
];

window.moviesTamil = moviesTamil;
