const moviesHindi = [
  { id: 7, title: "3 Idiots", language: "Hindi", genre: ["Comedy", "Drama"], year: 2009, rating: 8.4, plot: "Two friends are searching for their lost companion, recalling their college days and their friend who inspired them to excel.", poster: "posters/3_idiots.jpg", cast: ["Aamir Khan", "R. Madhavan", "Sharman Joshi"], duration: "2h 50m" },
  { id: 8, title: "Sholay", language: "Hindi", genre: ["Action", "Drama"], year: 1975, rating: 8.1, plot: "A retired police officer recruits two convicts to capture the bandit who massacred his family and bring him to justice.", poster: "posters/sholay.jpg", cast: ["Amitabh Bachchan", "Dharmendra", "Sanjeev Kumar"], duration: "3h 24m" },
  { id: 9, title: "Tumbbad", language: "Hindi", genre: ["Horror", "Thriller", "Drama"], year: 2018, rating: 8.2, plot: "A mythological story about a family who builds a shrine for Hastar in search of unlimited wealth, leading to ruin.", poster: "posters/tumbbad.jpg", cast: ["Sohum Shah", "Jyoti Malshe", "Rudrapriya Singh"], duration: "1h 44m" },
  { id: 10, title: "Drishyam", language: "Hindi", genre: ["Thriller", "Drama"], year: 2015, rating: 8.2, plot: "A common cable operator tries to protect his family from police prosecution when they accidentally commit a crime.", poster: "posters/drishyam.jpg", cast: ["Ajay Devgn", "Tabu", "Shriya Saran"], duration: "2h 43m" },
  { id: 11, title: "Dangal", language: "Hindi", genre: ["Drama", "Action"], year: 2016, rating: 8.3, plot: "Former wrestler Mahavir Phogat struggles to train his daughters towards glory in the face of societal oppression.", poster: "posters/dangal.jpg", cast: ["Aamir Khan", "Sakshi Tanwar", "Fatima Sana Shaikh"], duration: "2h 41m" },
  { id: 12, title: "Andhadhun", language: "Hindi", genre: ["Comedy", "Thriller"], year: 2018, rating: 8.2, plot: "A series of mysterious events changes the life of a blind pianist who must now report a crime he should not have seen.", poster: "posters/andhadhun.jpg", cast: ["Ayushmann Khurrana", "Tabu", "Radhika Apte"], duration: "2h 19m" },
  { id: 31, title: "Lagaan", language: "Hindi", genre: ["Drama"], year: 2001, rating: 8.1, plot: "The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers.", poster: "posters/lagaan.jpg", cast: ["Aamir Khan", "Gracy Singh", "Rachel Shelley"], duration: "3h 44m" },
  { id: 32, title: "Dilwale Dulhania Le Jayenge", language: "Hindi", genre: ["Drama", "Comedy"], year: 1995, rating: 8.0, plot: "A young man and woman fall in love during a European vacation, but the boy must win over the girl's traditional family.", poster: "posters/ddlj.jpg", cast: ["Shah Rukh Khan", "Kajol", "Amrish Puri"], duration: "3h 9m" },
  { id: 33, title: "Gangs of Wasseypur", language: "Hindi", genre: ["Action", "Thriller"], year: 2012, rating: 8.2, plot: "A clash between a coal mining mafia lord and the son of a worker leads to a deadly multi-generational turf war of vengeance.", poster: "posters/wasseypur.jpg", cast: ["Manoj Bajpayee", "Nawazuddin Siddiqui", "Richa Chaddha"], duration: "5h 21m" },
  { id: 34, title: "Zindagi Na Milegi Dobara", language: "Hindi", genre: ["Drama", "Comedy"], year: 2011, rating: 8.2, plot: "Three childhood friends take a bachelor trip to Spain, where they confront their deepest fears and learn to live.", poster: "posters/znmd.jpg", cast: ["Hrithik Roshan", "Farhan Akhtar", "Abhay Deol"], duration: "2h 35m" },
  { id: 35, title: "Queen", language: "Hindi", genre: ["Comedy", "Drama"], year: 2013, rating: 8.1, plot: "A Delhi girl from a traditional family goes on her honeymoon trip to Paris and Amsterdam alone after being stood up.", poster: "posters/queen.jpg", cast: ["Kangana Ranaut", "Rajkummar Rao", "Lisa Haydon"], duration: "2h 26m" },
  { id: 36, title: "PK", language: "Hindi", genre: ["Comedy", "Sci-Fi"], year: 2014, rating: 8.1, plot: "An alien on Earth loses his communication device and asks innocent questions that expose the dogmas of religions.", poster: "posters/pk.jpg", cast: ["Aamir Khan", "Anushka Sharma", "Sushant Singh Rajput"], duration: "2h 33m" },
  { id: 37, title: "Shershaah", language: "Hindi", genre: ["Drama", "Action"], year: 2021, rating: 8.4, plot: "The story of Indian army officer Captain Vikram Batra, who fought valiantly during the 1999 Kargil War and became a national hero.", poster: "posters/shershaah.jpg", cast: ["Sidharth Malhotra", "Kiara Advani", "Shiv Panditt"], duration: "2h 15m" },
  { id: 38, title: "Bajrangi Bhaijaan", language: "Hindi", genre: ["Drama", "Comedy"], year: 2015, rating: 8.1, plot: "A simple Indian man with a magnanimous heart embarks on a dangerous journey to reunite a mute Pakistani girl with her family.", poster: "posters/bajrangi.jpg", cast: ["Salman Khan", "Kareena Kapoor", "Nawazuddin Siddiqui"], duration: "2h 39m" },
  { id: 39, title: "Barfi!", language: "Hindi", genre: ["Comedy", "Drama"], year: 2012, rating: 8.1, plot: "Three young people learn that love can neither be defined by society's norms nor by physical challenges.", poster: "posters/barfi.jpg", cast: ["Ranbir Kapoor", "Priyanka Chopra", "Ileana D'Cruz"], duration: "2h 30m" },
  { id: 40, title: "Swades", language: "Hindi", genre: ["Drama"], year: 2004, rating: 8.2, plot: "A successful Indian scientist working at NASA returns to his home village in India to find his childhood nanny.", poster: "posters/swades.jpg", cast: ["Shah Rukh Khan", "Gayatri Joshi", "Kishori Ballal"], duration: "3h 10m" }
];

window.moviesHindi = moviesHindi;
